### ISSUE TITLE
delete source request returns Account instead of Source

### ISSUE THREAD

**Issue by ktravers** [stripe/stripe-mock#131]
When responding to delete source request, stripe-mock returns an Account object:

```bash
$ curl -X DELETE http://localhost:12111/v1/customers/cus_123/sources/src_123 -H "Authorization: Bearer sk_test_123"
{
  "business_logo": null,
  "business_name": null,
  "business_url": null,
  "charges_enabled": false,
  "country": "US",
  "created": 1234567890,
  "debit_negative_balances": true,
  "decline_charge_on": {
    "avs_failure": true,
    "cvc_failure": true
  },
  "default_currency": "usd",
  "details_submitted": false,
  "display_name": null,
  "email": "site@stripe.com",
  "external_accounts": {
    "data": [
      {
        "account_holder_name": "Jane Austen",
        "account_holder_type": "individual",
        "bank_name": "STRIPE TEST BANK",
        "country": "US",
        "currency": "usd",
        "customer": null,
        "fingerprint": "1JWtPxqbdX5Gamtz",
        "id": "ba_1Djh6mIsTqXCURuYctvSjksI",
        "last4": "6789",
        "metadata": {},
        "object": "bank_account",
        "routing_number": "110000000",
        "status": "new"
      }
    ],
    "has_more": false,
    "object": "list",
    "url": "/v1/accounts/src_123/external_accounts"
  },
  "id": "src_123",
  "legal_entity": {
    "additional_owners": [],
    "address": {
      "city": null,
      "country": "US",
      "line1": null,
      "line2": null,
      "postal_code": null,
      "state": null
    },
    "business_name": null,
    "business_tax_id_provided": false,
    "dob": {
      "day": null,
      "month": null,
      "year": null
    },
    "first_name": null,
    "last_name": null,
    "personal_address": {
      "city": null,
      "country": "US",
      "line1": null,
      "line2": null,
      "postal_code": null,
      "state": null
    },
    "personal_id_number_provided": false,
    "ssn_last_4_provided": false,
    "type": null,
    "verification": {
      "details": null,
      "details_code": null,
      "document": null,
      "document_back": null,
      "status": "unverified"
    }
  },
  "metadata": {},
  "object": "account",
  "payout_schedule": {
    "delay_days": 2,
    "interval": "daily"
  },
  "payout_statement_descriptor": null,
  "payouts_enabled": false,
  "product_description": null,
  "statement_descriptor": null,
  "support_address": null,
  "support_email": null,
  "support_phone": null,
  "timezone": "Etc/UTC",
  "tos_acceptance": {
    "date": null,
    "ip": null,
    "user_agent": null
  },
  "type": "standard",
  "verification": {
    "disabled_reason": "fields_needed",
    "due_by": null,
    "fields_needed": [
      "business_url",
      "external_account",
      "legal_entity.address.city",
      "legal_entity.address.line1",
      "legal_entity.address.postal_code",
      "legal_entity.address.state",
      "legal_entity.dob.day",
      "legal_entity.dob.month",
      "legal_entity.dob.year",
      "legal_entity.first_name",
      "legal_entity.last_name",
      "legal_entity.type",
      "product_description",
      "support_phone",
      "tos_acceptance.date",
      "tos_acceptance.ip"
    ]
  }
}
```

When responding to delete source request, the live Stripe API returns a Source object:
```bash
$ curl -X DELETE https://api.stripe.com/v1/customers/$CUSTOMER_ID/sources/$SOURCE_ID -u $STRIPE_SECRET_KEY:
{
  "id": "src_abc123",
  "object": "source",
  "ach_credit_transfer": {
    "account_number": "test_abc123",
    "bank_name": "TEST BANK",
    "fingerprint": "fIoh668vkTgg7nKU",
    "routing_number": "110000000",
    "swift_code": "TSTEZ122",
    "refund_routing_number": null,
    "refund_account_number": null,
    "refund_account_holder_type": null,
    "refund_account_holder_name": null
  },
  "amount": null,
  "client_secret": "src_client_secret_abc123",
  "created": 1539663457,
  "currency": "usd",
  "flow": "receiver",
  "livemode": false,
  "metadata": {
  },
  "owner": {
    "address": null,
    "email": "amount_0@stripe.com",
    "name": null,
    "phone": null,
    "verified_address": null,
    "verified_email": null,
    "verified_name": null,
    "verified_phone": null
  },
  "receiver": {
    "address": "110000000-test_abc123",
    "amount_charged": 0,
    "amount_received": 0,
    "amount_returned": 0,
    "refund_attributes_method": "email",
    "refund_attributes_status": "missing"
  },
  "statement_descriptor": null,
  "status": "consumed",
  "type": "ach_credit_transfer",
  "usage": "reusable"
}
```

**Comment by ob-stripe** [comment]
This is basically the same issue as #36. stripe-mock currently ignores the input and just returns a resource that's compatible with the endpoint.

In this case, the spec lists the following resources for `DELETE /v1/customers/{customer}/sources/{id}`:
```yaml
            application/json:
              schema:
                anyOf:
                - "$ref": "#/components/schemas/payment_source"
                - "$ref": "#/components/schemas/deleted_payment_source"
```

and `payment_source` is defined like so:
```yaml
    payment_source:
      anyOf:
      - "$ref": "#/components/schemas/account"
      - "$ref": "#/components/schemas/alipay_account"
      - "$ref": "#/components/schemas/bank_account"
      - "$ref": "#/components/schemas/bitcoin_receiver"
      - "$ref": "#/components/schemas/card"
      - "$ref": "#/components/schemas/payment_method"
      - "$ref": "#/components/schemas/source"
```

so stripe-mock returns an `account`.

I'm a bit surprised though because for `DELETE` requests, stripe-mock should favor the deleted version of the resource (cf. #89). My guess is that the polymorphic interface is causing the heuristic to fail. (Note that even if it were working, the first resource defined in `deleted_payment_source` is `deleted_alipay_account`, which isn't a great default choice either...)

In any case, I think we should close this as a dupe of #36, but I'll let @brandur-stripe decide.
