### ISSUE TITLE
Docker Compose exit code 143

### ISSUE THREAD

**Issue by Lzok** [stripe/stripe-mock#286]
Hello, how are you?

I wanted to ask if this is ok or if it's some problem with the stripe-mock docker image. I'm running some tests on my api, they ran ok and exit ok with code 0 but the stripe-mock container is exiting with code 143.

The portion of my docker-compose:
```yaml
stripe-mock:
    image: stripemock/stripe-mock:latest
    container_name: stripe-mock-server
    ports:
      - 12111:12111
      - 12112:12112
    restart: unless-stopped

backend:
  ...etc
```

I'm running my suite like this: `docker compose -f docker-compose-test.yml up --exit-code-from backend`

<img width="319" alt="image" src="https://user-images.githubusercontent.com/45211582/157339073-7ce30d45-d356-4fac-adda-0852810b0bf8.png">

Thanks in advance!
